# Insights

## Setup

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [5]:
posts = pd.read_csv('posts.csv')
posts.head()

,post_id,date,post_text,link,impressions,likes,engagements,bookmarks,share,new follows,replies,reposts,profile_visits,detail_expands,url_clicks,hashtag_clicks,permalink_clicks
0,1939692818768724028,"Mon, Jun 30, 2025",@rudrankriyam snuff is one of my favorite song...,https://x.com/bodhichristian/status/1939692818...,101,0,6,0,0,0,1,0,1,4,0,0,0
1,1937876171934347337,"Wed, Jun 25, 2025",🚨 heat advisory,https://x.com/bodhichristian/status/1937876171...,279,4,6,0,0,0,0,0,0,2,0,0,0
2,1937598816963952922,"Tue, Jun 24, 2025",PEOPLE OF THE WORLD https://t.co/Mv5u8G6dTJ,https://x.com/bodhichristian/status/1937598816...,393,1,9,0,0,0,0,0,2,1,0,0,0
3,1937561131737928009,"Tue, Jun 24, 2025",this is an amazing read. @AirbnbEng shares an ...,https://x.com/bodhichristian/status/1937561131...,775,6,16,1,0,0,0,1,6,3,0,0,0
4,1937535378254180450,"Tue, Jun 24, 2025",did some rearranging. come say hi over at @sem...,https://x.com/bodhichristian/status/1937535378...,438,4,4,0,0,0,0,0,0,0,0,0,0

In [9]:
columns = ['post_id', 'link', 'url_clicks', 'hashtag_clicks', 'permalink_clicks']
posts_df = posts.drop(columns, axis=1)
posts_df.head()

,date,post_text,impressions,likes,engagements,bookmarks,share,new follows,replies,reposts,profile_visits,detail_expands
0,"Mon, Jun 30, 2025",@rudrankriyam snuff is one of my favorite song...,101,0,6,0,0,0,1,0,1,4
1,"Wed, Jun 25, 2025",🚨 heat advisory,279,4,6,0,0,0,0,0,0,2
2,"Tue, Jun 24, 2025",PEOPLE OF THE WORLD https://t.co/Mv5u8G6dTJ,393,1,9,0,0,0,0,0,2,1
3,"Tue, Jun 24, 2025",this is an amazing read. @AirbnbEng shares an ...,775,6,16,1,0,0,0,1,6,3
4,"Tue, Jun 24, 2025",did some rearranging. come say hi over at @sem...,438,4,4,0,0,0,0,0,0,0